### ISSUE TITLE
Figure out if we can use the matrix strategy for linux builds

### ISSUE THREAD

**Issue by autarch** [houseabsolute/ci-perl-helpers#11]
The current linux templates is super repetitive. Can we use a matrix instead?

**Comment by autarch** [comment]
I don't see a good way to do this. Azure doesn't support combining a matrix with templates like this:

```yaml
stages:
  - stage: Stage
    jobs:
      - job: GenerateMatrix
        steps:
          - bash: |
              echo '##vso[task.setVariable variable=matrix]{ "template": "foo.yml", "params": { "size": 42, "color": "blue" } }'
            name: matrixGenerator

      - job: UseMatrix
        dependsOn: GenerateMatrix
        strategy:
          matrix: $[ dependencies.GenerateMatrix.outputs['matrixGenerator.matrix'] ]
        template: $(template)
        parameters: $(params)
```

This gives these errors:

* /azure-pipelines.yml (Line: 14, Col: 9): Unexpected value 'template'
* /azure-pipelines.yml (Line: 15, Col: 9): Unexpected value 'parameters'
