### ISSUE TITLE
Fails

### ISSUE THREAD

**Issue by nigelhorne** [houseabsolute/ci-perl-helpers#18]
Thanks for the contribution - it should be very helpful.  However when I use your YAML file, I get this error:

`
Repository ci-perl-helpers references endpoint houseabsolute/ci-perl-helpers which does not exist or is not authorized for use`

Any suggestions?

**Comment by autarch** [comment]
Please share your `azure-pipelines.yml` here.

**Comment by autarch** [comment]
Also, can you point me to your repo that's using this?

**Comment by nigelhorne** [comment]
Here is the azure-pipelines.yml - straight from your readme:

```
resources:
  repositories:
    - repository: ci-perl-helpers
      type: github
      name: houseabsolute/ci-perl-helpers
      endpoint: houseabsolute/ci-perl-helpers

stages:
  - template: templates/build.yml@ci-perl-helpers
  - template: templates/linux.yml@ci-perl-helpers
    parameters:
      test_xt: true
      use_default_perls: true
  - template: templates/macos.yml@ci-perl-helpers
    parameters:
      use_default_perls: true
  - template: templates/windows.yml@ci-perl-helpers
    parameters:
      use_default_perls: true
```
